name: sharing_cafe
description: An app to meet up for coffee with strangers. Dating, Social & Share.
publish_to: 'none' #

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9 # help us to use SVG in our app
  provider: ^6.1.1 # for State management
  flutter_html: ^3.0.0-beta.2
  flutter_quill: ^9.3.1
  http: ^1.2.1
  fluttertoast: ^8.2.4
  card_swiper: ^3.0.1
  shared_preferences: ^2.2.2
  dio: ^5.4.1
  image_picker: ^1.0.7
  socket_io_client: ^2.0.3+1
  line_awesome_flutter: ^2.0.0
  multi_dropdown: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Opensans
      fonts:
        - asset: assets/fonts/opensans/OpenSans-Regular.ttf
        - asset: assets/fonts/opensans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/opensans/OpenSans-Light.ttf
          weight: 300